language: node_js
node_js:
  - "8"
cache:
  directories:
    - node_modules
script:
  - npm ci || travis_terminate 1
  - npm run lint
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: dist
  keep-history: true
  fqdn: gameofthronesintrocreator.kassellabs.io
  on:
    branch: master
notifications:
  webhooks: https://fathomless-fjord-24024.herokuapp.com/notify